# Generated by Django 3.1.4 on 2021-01-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(help_text='Choose a category:             H -> House            J -> Job            S -> Sale            O -> Other', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ads.category'),
        ),
    ]
