# Generated by Django 3.1.4 on 2021-01-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_auto_20210103_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(help_text='Choose a category:             House,            Job,            Sale,            Other', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ads.category'),
        ),
    ]
